package ir.khajavy.supermarket;

import android.app.Dialog;
import android.content.Intent;
import android.graphics.BitmapFactory;
import android.net.Uri;
import android.text.InputType;
import android.view.View;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;

import org.json.JSONArray;
import org.json.JSONObject;

import java.util.Iterator;

/** v2.0 — reports, accounting, users, audit, settings (21 categories), store, SMS, hardware, diagnostics, support. */
public final class AdminScreens {
    private AdminScreens() {}

    /* ---------------- Reports ---------------- */
    public static final class Reports extends Screens.Screen {
        int tab; int days = 7;
        static final String[] TABS = {"فروش", "صندوق‌داران", "موجودی", "انقضا", "کمبود", "بچ‌ها", "سود", "هزینهٔ خرید", "اصلاحات", "انبارگردانی‌ها"};
        Reports(AppActivity a) { this(a, 0); } Reports(AppActivity a, int tab) { super(a); this.tab = tab; }
        public String key() { return "reports"; } public String title() { return "گزارش‌ها"; }
        public void load() {
            clear(); LinearLayout ch = Ui.row(c); for (int i = 0; i < TABS.length; i++) { final int k = i; ch.addView(Ui.chip(c, TABS[i], i == tab, () -> { tab = k; load(); })); } body.addView(Ui.chips(c, ch));
            LinearLayout out = Ui.col(c); body.addView(out); out.addView(Ui.empty(c, "…"));
            String from = Jalali.daysAgoIso(days), to = Jalali.todayIso();
            switch (tab) {
                case 0: { LinearLayout rg = Ui.row(c); for (int d : new int[]{1, 7, 30, 90}) rg.addView(Ui.chip(c, d == 1 ? "امروز" : Ui.num(d) + " روز", days == d, () -> { days = d; load(); })); body.addView(rg, 1); get("/reports/sales?start=" + (days == 1 ? to : from) + "&end=" + to + "&group=daily", r -> { JSONObject d = (JSONObject) r; out.removeAllViews(); out.addView(Ui.grid2(c, Ui.kpi(c, "جمع فروش", Ui.money(d.optDouble("total_sales")), null, Ui.GREEN), Ui.kpi(c, "تعداد فاکتور", Ui.num(d.optDouble("invoice_count")), null, Ui.PRIMARY))); JSONArray g = d.optJSONArray("groups"); LinearLayout cd = Ui.card(c, "به تفکیک روز"); for (int i = 0; g != null && i < g.length(); i++) { JSONObject x = g.optJSONObject(i); cd.addView(Ui.kv(c, Ui.jdate(x.optString("date")), Ui.num(x.optDouble("invoice_count")) + " فاکتور · " + Ui.money(x.optDouble("total")), 0)); } if (g == null || g.length() == 0) cd.addView(Ui.muted(c, "فروشی در این بازه نیست")); out.addView(cd); }); get("/reports/sales?start=" + (days == 1 ? to : from) + "&end=" + to + "&group=product", r -> { JSONArray g = ((JSONObject) r).optJSONArray("groups"); if (g == null || g.length() == 0) return; LinearLayout cd = Ui.card(c, "به تفکیک کالا"); for (int i = 0; i < Math.min(15, g.length()); i++) { JSONObject x = g.optJSONObject(i); cd.addView(Ui.kv(c, s(x, "name", s(x, "product_name")), Ui.num(x.optDouble("qty", x.optDouble("quantity"))) + " · " + Ui.money(x.optDouble("total")), 0)); } out.addView(cd); }); break; }
                case 1: get("/reports/cashiers", r -> { JSONArray ar = arr(r); out.removeAllViews(); if (ar.length() == 0) out.addView(Ui.empty(c, "—")); for (int i = 0; i < ar.length(); i++) { JSONObject x = ar.optJSONObject(i); LinearLayout cd = Ui.card(c, x.optString("username")); cd.addView(Ui.kv(c, "فاکتور", Ui.num(x.optDouble("invoice_count")), 0)); cd.addView(Ui.kv(c, "فروش", Ui.money(x.optDouble("total_sales")), Ui.GREEN)); cd.addView(Ui.kv(c, "تخفیف", Ui.money(x.optDouble("total_discount")), 0)); if (Screens.can("pricing.view_cost")) cd.addView(Ui.kv(c, "سود", Ui.money(x.optDouble("profit")), 0)); out.addView(cd); } }); break;
                case 2: get("/reports/inventory", r -> { JSONArray ar = arr(r); out.removeAllViews(); double tv = 0; for (int i = 0; i < ar.length(); i++) tv += ar.optJSONObject(i).optDouble("value_at_cost"); out.addView(Ui.kpi(c, "ارزش کل موجودی (قیمت خرید)", Ui.money(tv), Ui.num(ar.length()) + " کالا", Ui.AMBER)); LinearLayout cd = Ui.card(c, "کالاها"); for (int i = 0; i < ar.length(); i++) { JSONObject x = ar.optJSONObject(i); cd.addView(Ui.kv(c, x.optString("name"), Ui.num(x.optDouble("total_qty")) + " · " + Ui.money(x.optDouble("value_at_cost")), x.optDouble("total_qty") <= x.optDouble("min_stock_alert") ? Ui.RED : 0)); } out.addView(cd); }); break;
                case 3: get("/reports/expiry", r -> { JSONObject ex = (JSONObject) r; out.removeAllViews(); String[][] EK = {{"EXPIRED", "منقضی‌شده"}, {"EXPIRING_TODAY", "امروز"}, {"EXPIRING_3_DAYS", "تا ۳ روز"}, {"EXPIRING_7_DAYS", "تا ۷ روز"}, {"EXPIRING_30_DAYS", "تا ۳۰ روز"}}; boolean any = false; for (String[] k : EK) { JSONArray ar = ex.optJSONArray(k[0]); if (ar == null || ar.length() == 0) continue; any = true; LinearLayout cd = Ui.card(c, k[1]); for (int i = 0; i < ar.length(); i++) { JSONObject b = ar.optJSONObject(i); cd.addView(Ui.kv(c, s(b, "product_name", s(b, "name")), Ui.num(b.optDouble("current_qty")) + " · " + Ui.jdate(s(b, "expiry_date")), "EXPIRED".equals(k[0]) ? Ui.RED : Ui.AMBER)); } out.addView(cd); } if (!any) out.addView(Ui.empty(c, "کالای نزدیک انقضا نیست")); }); break;
                case 4: get("/reports/low-stock", r -> { JSONArray ar = arr(r); out.removeAllViews(); if (ar.length() == 0) out.addView(Ui.empty(c, "کمبودی نیست")); for (int i = 0; i < ar.length(); i++) { JSONObject x = ar.optJSONObject(i); out.addView(Ui.item(c, x.optString("name"), "حد هشدار " + Ui.num(x.optDouble("min_stock_alert")), Ui.num(x.optDouble("total_stock", x.optDouble("total_qty"))), Ui.RED, null)); } }); break;
                case 5: get("/reports/batches", r -> { out.removeAllViews(); render(out, r, "بچ‌ها"); }); break;
                case 6: if (!Screens.can("pricing.view_cost")) { out.removeAllViews(); out.addView(Ui.empty(c, "دسترسی مشاهدهٔ سود ندارید")); break; } get("/reports/profit", r -> { JSONArray ar = arr(r); out.removeAllViews(); double tp = 0, tr = 0; for (int i = 0; i < ar.length(); i++) { tp += ar.optJSONObject(i).optDouble("profit"); tr += ar.optJSONObject(i).optDouble("revenue"); } out.addView(Ui.grid2(c, Ui.kpi(c, "درآمد", Ui.money(tr), null, Ui.GREEN), Ui.kpi(c, "سود", Ui.money(tp), tr > 0 ? Ui.num(Math.round(tp * 1000 / tr) / 10.0) + "٪ حاشیه" : null, Ui.VIOLET))); LinearLayout cd = Ui.card(c, "به تفکیک بچ"); for (int i = 0; i < Math.min(50, ar.length()); i++) { JSONObject x = ar.optJSONObject(i); JSONObject p = Db.productById(x.optLong("product_id")); cd.addView(Ui.kv(c, (p == null ? "کالا #" + x.optLong("product_id") : p.optString("name")) + " · " + Ui.num(x.optDouble("qty")), Ui.money(x.optDouble("profit")), 0)); } out.addView(cd); }); break;
                case 7: get("/reports/purchase-cost", r -> { out.removeAllViews(); render(out, r, "هزینهٔ خرید"); }); break;
                case 8: get("/reports/adjustments", r -> { out.removeAllViews(); render(out, r, "اصلاحات موجودی"); }); break;
                case 9: get("/reports/stocktakes", r -> { out.removeAllViews(); render(out, r, "انبارگردانی‌ها"); }); break;
            }
        }
        /** generic renderer for tabular reports: any list of objects or object of scalars. */
        void render(LinearLayout out, Object r, String title) {
            if (r instanceof JSONArray) { JSONArray ar = (JSONArray) r; if (ar.length() == 0) { out.addView(Ui.empty(c, "داده‌ای نیست")); return; } if (ar.optJSONObject(0) == null) { LinearLayout cd = Ui.card(c, title); StringBuilder sb = new StringBuilder(); for (int i = 0; i < ar.length(); i++) sb.append(i > 0 ? "، " : "").append(Ui.fa(ar.optString(i))); cd.addView(Ui.body(c, sb.toString())); out.addView(cd); return; } for (int i = 0; i < Math.min(80, ar.length()); i++) { JSONObject x = ar.optJSONObject(i); if (x == null) continue; LinearLayout cd = Ui.card(c, null); Iterator<String> it = x.keys(); while (it.hasNext()) { String k = it.next(); Object v = x.opt(k); if (v instanceof JSONArray || v instanceof JSONObject) continue; cd.addView(Ui.kv(c, LBL(k), fmt(k, v), 0)); } out.addView(cd); } }
            else if (r instanceof JSONObject) { JSONObject x = (JSONObject) r; LinearLayout cd = Ui.card(c, title); Iterator<String> it = x.keys(); while (it.hasNext()) { String k = it.next(); Object v = x.opt(k); if (v instanceof JSONArray) { render(out, v, LBL(k)); continue; } if (v instanceof JSONObject) { JSONObject sub = (JSONObject) v; LinearLayout sc = Ui.card(c, LBL(k)); Iterator<String> it2 = sub.keys(); while (it2.hasNext()) { String k2 = it2.next(); Object v2 = sub.opt(k2); if (v2 instanceof JSONArray) { JSONArray ar = (JSONArray) v2; for (int i = 0; i < ar.length(); i++) { JSONObject row = ar.optJSONObject(i); if (row != null) sc.addView(Ui.kv(c, Ui.fa(s(row, "code")) + " " + s(row, "name", s(row, "label")), fmt("amount", row.opt(row.has("amount") ? "amount" : row.has("total") ? "total" : "balance")), 0)); } } else if (!(v2 instanceof JSONObject)) sc.addView(Ui.kv(c, LBL(k2), fmt(k2, v2), 0)); } out.addView(sc); continue; } cd.addView(Ui.kv(c, LBL(k), fmt(k, v), 0)); } out.addView(cd, 0); }
        }
        static String fmt(String k, Object v) { if (v == null || JSONObject.NULL.equals(v)) return "—"; if (v instanceof Number) { double d = ((Number) v).doubleValue(); return k.contains("price") || k.contains("cost") || k.contains("value") || k.contains("total") || k.contains("amount") || k.contains("revenue") || k.contains("profit") ? Ui.money(d) : Ui.num(d); } String s = String.valueOf(v); return s.matches("\\d{4}-\\d{2}-\\d{2}.*") ? Ui.jdate(s) : Ui.fa(s); }
        static final String[][] L = {{"product_name", "کالا"}, {"name", "نام"}, {"barcode", "بارکد"}, {"batch_number", "بچ"}, {"qty", "تعداد"}, {"quantity", "تعداد"}, {"total_qty", "موجودی"}, {"buy_price", "قیمت خرید"}, {"sell_price", "قیمت فروش"}, {"total_cost", "هزینهٔ کل"}, {"cost", "هزینه"}, {"received_at", "تاریخ دریافت"}, {"created_at", "تاریخ"}, {"reason", "دلیل"}, {"difference", "اختلاف"}, {"status", "وضعیت"}, {"count", "تعداد"}, {"total", "جمع"}, {"movement_type", "نوع"}, {"user", "کاربر"}, {"username", "کاربر"}, {"value", "ارزش"}, {"approved_at", "تأیید"}, {"completed_at", "پایان"}, {"started_at", "شروع"}, {"items", "اقلام"}, {"system_qty", "سیستم"}, {"physical_qty", "فیزیکی"}, {"expiry_date", "انقضا"}, {"supplier", "تأمین‌کننده"}, {"note", "توضیح"}, {"id", "شناسه"}, {"product_id", "شناسهٔ کالا"}, {"batch_id", "شناسهٔ بچ"}, {"period", "بازه"}, {"month", "ماه"}, {"date", "تاریخ"}, {"value_at_cost", "ارزش خرید"}, {"total_value", "ارزش کل"}, {"invoice_count", "فاکتور"}, {"counted", "شمارش‌شده"}, {"percent", "درصد"}, {"remaining", "مانده"}, {"before", "قبل"}, {"after", "بعد"}, {"delta", "تغییر"}, {"new_qty", "مقدار جدید"}, {"old_qty", "مقدار قبلی"}, {"quantity_received", "دریافتی"}, {"current_qty", "مانده"}, {"supplier_price", "قیمت تأمین‌کننده"}, {"discount", "تخفیف"}, {"tax", "مالیات"}, {"total_received", "جمع دریافتی"}, {"total_purchase", "جمع خرید"}, {"batches", "بچ‌ها"}, {"assets", "دارایی‌ها"}, {"liabilities", "بدهی‌ها"}, {"equity", "حقوق صاحبان"}, {"revenue", "درآمد"}, {"expenses", "هزینه‌ها"}, {"cogs", "بهای تمام‌شده"}, {"gross_profit", "سود ناخالص"}, {"net_profit", "سود خالص"}, {"as_of", "تا تاریخ"}, {"start", "از"}, {"end", "تا"}, {"active_count", "بچ فعال"}, {"active", "فعال"}, {"sold_out", "تمام‌شده"}, {"expired", "منقضی"}, {"blocked", "مسدود"}, {"qty_received", "دریافتی"}, {"balanced", "متوازن"}, {"total_assets", "جمع دارایی"}, {"total_liabilities", "جمع بدهی"}, {"total_equity", "جمع حقوق"}};
        static String LBL(String k) { for (String[] l : L) if (l[0].equals(k)) return l[1]; return k; }
    }

    /* ---------------- Accounting ---------------- */
    public static final class Accounting extends Screens.Screen {
        int tab = 0;
        static final String[] TABS = {"نمای کلی", "صندوق روز", "هزینه‌ها", "تأمین‌کنندگان", "چک‌ها", "دفتر روزنامه", "تراز آزمایشی", "سود و زیان", "ترازنامه", "حساب‌ها"};
        Accounting(AppActivity a) { super(a); }
        public String key() { return "accounting"; } public String title() { return "حسابداری"; }
        public void load() {
            clear(); LinearLayout ch = Ui.row(c); for (int i = 0; i < TABS.length; i++) { final int k = i; ch.addView(Ui.chip(c, TABS[i], i == tab, () -> { tab = k; load(); })); } body.addView(Ui.chips(c, ch)); LinearLayout out = Ui.col(c); body.addView(out); out.addView(Ui.empty(c, "…"));
            switch (tab) {
                case 0: get("/accounting/overview", r -> { JSONObject o = (JSONObject) r; out.removeAllViews(); out.addView(Ui.grid2(c, Ui.kpi(c, "صندوق", Ui.money(o.optDouble("cash")), null, Ui.GREEN), Ui.kpi(c, "بانک / کارت", Ui.money(o.optDouble("bank") + o.optDouble("card")), null, Ui.PRIMARY))); out.addView(Ui.grid2(c, Ui.kpi(c, "مطالبات", Ui.money(o.optDouble("receivables")), null, Ui.AMBER), Ui.kpi(c, "بدهی‌ها", Ui.money(o.optDouble("payables")), null, Ui.RED))); JSONObject m = o.optJSONObject("month"); LinearLayout cd = Ui.card(c, "این ماه"); cd.addView(Ui.kv(c, "درآمد", Ui.money(d(m, "revenue")), Ui.GREEN)); cd.addView(Ui.kv(c, "بهای تمام‌شده", Ui.money(d(m, "cogs")), 0)); cd.addView(Ui.kv(c, "هزینه‌ها", Ui.money(d(m, "expenses")), 0)); cd.addView(Ui.kv(c, "سود خالص", Ui.money(d(m, "net_profit")), d(m, "net_profit") >= 0 ? Ui.GREEN : Ui.RED)); cd.addView(Ui.kv(c, "حاشیهٔ ناخالص", Ui.num(d(m, "gross_margin_pct")) + "٪", 0)); cd.addView(Ui.kv(c, "ارزش موجودی", Ui.money(o.optDouble("inventory_value")), 0)); out.addView(cd); JSONObject cq = o.optJSONObject("cheques"); LinearLayout cc = Ui.card(c, "چک‌ها"); cc.addView(Ui.kv(c, "دریافتی در جریان", Ui.num(d(cq, "received_count")) + " · " + Ui.money(d(cq, "received_pending")), 0)); cc.addView(Ui.kv(c, "پرداختی در جریان", Ui.num(d(cq, "issued_count")) + " · " + Ui.money(d(cq, "issued_pending")), 0)); JSONArray od = cq == null ? null : cq.optJSONArray("overdue"); if (od != null && od.length() > 0) cc.addView(Ui.kv(c, "سررسید گذشته", Ui.num(od.length()), Ui.RED)); out.addView(cc); }); break;
                case 1: get("/accounting/cash-sessions/current", r -> { out.removeAllViews(); JSONObject s = r instanceof JSONObject ? (JSONObject) r : null; LinearLayout cd = Ui.card(c, "صندوق روز (شیفت)"); if (s == null) { cd.addView(Ui.muted(c, "شیفتی باز نیست")); cd.addView(Ui.primary(c, "باز کردن صندوق", () -> Ui.prompt(c, "موجودی اولیهٔ صندوق", "0", true, v -> { JSONObject b = j(); putNum(b, "opening_float", Ui.numVal(new EditText(c) {{ setText(v); }}, 0)); post("/accounting/cash-sessions/open", b, x -> load()); }))); } else { cd.addView(Ui.kv(c, "باز شده", Ui.jdate(s.optString("opened_at")), 0)); cd.addView(Ui.kv(c, "موجودی اولیه", Ui.money(s.optDouble("opening_float")), 0)); cd.addView(Ui.kv(c, "فروش نقدی", Ui.money(s.optDouble("cash_sales", s.optDouble("expected_cash", 0))), 0)); cd.addView(Ui.kv(c, "موجودی مورد انتظار", Ui.money(s.optDouble("expected_cash")), Ui.GREEN)); cd.addView(Ui.danger(c, "بستن صندوق", () -> { LinearLayout l = Ui.col(c); EditText cnt = Ui.input(c, "وجه شمارش‌شده", true); EditText note = Ui.input(c, "توضیح"); l.addView(cnt); l.addView(note); Dialog[] dd = new Dialog[1]; l.addView(Ui.danger(c, "بستن", () -> { dd[0].dismiss(); JSONObject b = j("note", Ui.str(note)); putNum(b, "counted_cash", Ui.numVal(cnt, 0)); post("/accounting/cash-sessions/" + s.optLong("id") + "/close", b, x -> { JSONObject cs = (JSONObject) x; Ui.toast("بسته شد · مغایرت " + Ui.money(cs.optDouble("difference", 0))); load(); }); })); dd[0] = Ui.sheet(c, "بستن صندوق", l); })); } out.addView(cd); LinearLayout hs = Ui.card(c, "شیفت‌های قبلی"); out.addView(hs); getQuiet("/accounting/cash-sessions", r2 -> { JSONArray ar = arr(r2); if (ar.length() == 0) hs.addView(Ui.muted(c, "—")); for (int i = 0; i < Math.min(15, ar.length()); i++) { JSONObject x = ar.optJSONObject(i); hs.addView(Ui.kv(c, Ui.jdate(x.optString("opened_at")) + " · " + s(x, "status"), Ui.money(x.optDouble("counted_cash", x.optDouble("expected_cash"))) + (x.optDouble("difference", 0) != 0 ? " (" + Ui.money(x.optDouble("difference")) + ")" : ""), x.optDouble("difference", 0) != 0 ? Ui.AMBER : 0)); } }); }); break;
                case 2: get("/accounting/expenses", r -> { JSONObject o = (JSONObject) r; out.removeAllViews(); out.addView(Ui.kpi(c, "جمع هزینه‌ها", Ui.money(o.optDouble("total")), null, Ui.RED)); if (Screens.can("accounting.post")) out.addView(Ui.primary(c, "+ ثبت هزینه", this::newExpense)); JSONArray ar = o.optJSONArray("items"); if (ar == null || ar.length() == 0) out.addView(Ui.empty(c, "هزینه‌ای ثبت نشده")); for (int i = 0; ar != null && i < ar.length(); i++) { JSONObject x = ar.optJSONObject(i); out.addView(Ui.item(c, s(x, "category_name", s(x, "category", "هزینه")), Ui.jdate(s(x, "expense_date", s(x, "date"))) + " · " + s(x, "description") + " · " + label(s(x, "paid_from"), PAY), Ui.money(x.optDouble("amount")), Ui.RED, null)); } }); break;
                case 3: get("/accounting/suppliers", r -> { JSONArray ar = arr(r); out.removeAllViews(); if (Screens.can("accounting.post")) out.addView(Ui.primary(c, "+ تأمین‌کنندهٔ جدید", () -> { LinearLayout l = Ui.col(c); EditText n = Ui.input(c, "نام"); EditText ph = Ui.input(c, "تلفن", true); EditText ad = Ui.input(c, "آدرس"); l.addView(n); l.addView(ph); l.addView(ad); Dialog[] dd = new Dialog[1]; l.addView(Ui.primary(c, "ثبت", () -> { dd[0].dismiss(); post("/accounting/suppliers", j("name", Ui.str(n), "phone", Ui.str(ph), "address", Ui.str(ad)), x -> load()); })); dd[0] = Ui.sheet(c, "تأمین‌کننده", l); })); if (ar.length() == 0) out.addView(Ui.empty(c, "—")); for (int i = 0; i < ar.length(); i++) { JSONObject x = ar.optJSONObject(i); out.addView(Ui.item(c, x.optString("name"), Ui.fa(s(x, "phone")), "بدهی " + Ui.money(x.optDouble("balance", x.optDouble("payable", 0))), x.optDouble("balance", x.optDouble("payable", 0)) > 0 ? Ui.RED : Ui.GREEN, () -> { if (!Screens.can("accounting.post")) return; LinearLayout l = Ui.col(c); EditText amt = Ui.input(c, "مبلغ پرداخت", true); EditText note = Ui.input(c, "توضیح"); l.addView(amt); l.addView(note); Dialog[] dd = new Dialog[1]; l.addView(Ui.success(c, "ثبت پرداخت نقدی", () -> { dd[0].dismiss(); JSONObject b = j("method", "CASH", "note", Ui.str(note)); putNum(b, "amount", Ui.numVal(amt, 0)); post("/accounting/suppliers/" + x.optLong("id") + "/pay", b, y -> load()); })); dd[0] = Ui.sheet(c, "پرداخت به " + x.optString("name"), l); })); } }); break;
                case 4: get("/accounting/cheques", r -> { JSONArray ar = arr(r); out.removeAllViews(); if (Screens.can("accounting.post")) out.addView(Ui.primary(c, "+ ثبت چک", this::newCheque)); if (ar.length() == 0) out.addView(Ui.empty(c, "چکی ثبت نشده")); for (int i = 0; i < ar.length(); i++) { JSONObject x = ar.optJSONObject(i); out.addView(Ui.item(c, ("RECEIVED".equals(x.optString("direction")) ? "دریافتی" : "پرداختی") + " · " + Ui.fa(x.optString("number")), s(x, "party_name") + " · " + s(x, "bank_name") + " · سررسید " + Ui.jdate(x.optString("due_date")), Ui.money(x.optDouble("amount")) + "\n" + label(x.optString("status"), new String[][]{{"PENDING", "در جریان"}, {"CLEARED", "وصول"}, {"BOUNCED", "برگشتی"}}), stColor(x.optString("status")), () -> { if (!"PENDING".equals(x.optString("status")) || !Screens.can("accounting.post")) return; LinearLayout l = Ui.col(c); Dialog[] dd = new Dialog[1]; l.addView(Ui.success(c, "وصول شد", () -> { dd[0].dismiss(); post("/accounting/cheques/" + x.optLong("id") + "/clear", null, y -> load()); })); l.addView(Ui.danger(c, "برگشت خورد", () -> { dd[0].dismiss(); post("/accounting/cheques/" + x.optLong("id") + "/bounce", null, y -> load()); })); dd[0] = Ui.sheet(c, "چک " + Ui.fa(x.optString("number")), l); })); } }); break;
                case 5: get("/accounting/journal?limit=60", r -> { JSONArray ar = arr(r); out.removeAllViews(); if (ar.length() == 0) out.addView(Ui.empty(c, "—")); for (int i = 0; i < ar.length(); i++) { JSONObject x = ar.optJSONObject(i); out.addView(Ui.item(c, "#" + Ui.fa(String.valueOf(x.optInt("number"))) + " · " + x.optString("description"), Ui.jdate(x.optString("date")) + " · " + s(x, "kind") + " · " + s(x, "status"), Ui.money(x.optDouble("total")), stColor(x.optString("status")), () -> { LinearLayout l = Ui.col(c); JSONArray ls = x.optJSONArray("lines"); for (int k = 0; ls != null && k < ls.length(); k++) { JSONObject ln = ls.optJSONObject(k); l.addView(Ui.kv(c, Ui.fa(ln.optString("code")) + " " + ln.optString("name"), (ln.optDouble("debit") > 0 ? "بدهکار " + Ui.money(ln.optDouble("debit")) : "بستانکار " + Ui.money(ln.optDouble("credit"))), ln.optDouble("debit") > 0 ? Ui.AMBER : Ui.GREEN)); } if ("POSTED".equals(x.optString("status")) && Screens.can("accounting.post")) l.addView(Ui.danger(c, "سند معکوس", () -> Ui.prompt(c, "دلیل معکوس‌سازی", "", false, rs -> post("/accounting/journal/" + x.optLong("id") + "/reverse", j("reason", rs), y -> load())))); Ui.sheet(c, "سند " + Ui.fa(String.valueOf(x.optInt("number"))), l); })); } }); break;
                case 6: get("/accounting/trial-balance", r -> { JSONObject o = (JSONObject) r; out.removeAllViews(); out.addView(Ui.kpi(c, "تراز", o.optBoolean("balanced") ? "متوازن ✓" : "نامتوازن!", Ui.money(o.optDouble("total_debit")) + " / " + Ui.money(o.optDouble("total_credit")), o.optBoolean("balanced") ? Ui.GREEN : Ui.RED)); LinearLayout cd = Ui.card(c, null); JSONArray rows = o.optJSONArray("rows"); for (int i = 0; rows != null && i < rows.length(); i++) { JSONObject x = rows.optJSONObject(i); TextView t = Ui.text(c, (x.optBoolean("is_group") ? "" : "   ") + Ui.fa(x.optString("code")) + " " + x.optString("name"), 13, Ui.TEXT, x.optBoolean("is_group")); LinearLayout rw = Ui.row(c); t.setLayoutParams(Ui.weight(1)); rw.addView(t); rw.addView(Ui.text(c, Ui.money(x.optDouble("balance")), 13, x.optDouble("balance") < 0 ? Ui.RED : Ui.TEXT, true)); rw.setPadding(0, Ui.dp(4), 0, Ui.dp(4)); cd.addView(rw); } out.addView(cd); }); break;
                case 7: get("/accounting/income-statement?start=" + Jalali.daysAgoIso(30) + "&end=" + Jalali.todayIso(), r -> { out.removeAllViews(); new Reports(a).render(out, r, "سود و زیان"); }); break;
                case 8: get("/accounting/balance-sheet", r -> { out.removeAllViews(); new Reports(a).render(out, r, "ترازنامه"); }); break;
                case 9: get("/accounting/accounts", r -> { JSONArray ar = arr(r); out.removeAllViews(); LinearLayout cd = Ui.card(c, "سرفصل حساب‌ها"); for (int i = 0; i < ar.length(); i++) { JSONObject x = ar.optJSONObject(i); boolean grp = !x.optBoolean("is_postable"); cd.addView(Ui.kv(c, (grp ? "" : "   ") + Ui.fa(x.optString("code")) + " " + x.optString("name"), Ui.money(x.optDouble("balance")), 0)); } out.addView(cd); }); break;
            }
        }
        void newExpense() { getQuiet("/accounting/expense-categories", r -> { JSONArray cats = arr(r); LinearLayout l = Ui.col(c); final long[] cat = {cats.length() > 0 ? cats.optJSONObject(0).optLong("id") : 0}; LinearLayout ch = Ui.row(c); Runnable[] rd = new Runnable[1]; rd[0] = () -> { ch.removeAllViews(); for (int i = 0; i < cats.length(); i++) { JSONObject x = cats.optJSONObject(i); ch.addView(Ui.chip(c, x.optString("name"), x.optLong("id") == cat[0], () -> { cat[0] = x.optLong("id"); rd[0].run(); })); } }; rd[0].run(); l.addView(Ui.label(c, "دستهٔ هزینه")); l.addView(Ui.chips(c, ch)); l.addView(Ui.small(c, "+ دستهٔ جدید", () -> Ui.prompt(c, "نام دسته", "", false, n -> post("/accounting/expense-categories", j("name", n), x -> newExpense())))); EditText amt = Ui.input(c, "مبلغ", true); EditText desc = Ui.input(c, "شرح"); final String[] pf = {"CASH"}; LinearLayout pc = Ui.row(c); Runnable[] rp = new Runnable[1]; rp[0] = () -> { pc.removeAllViews(); for (String[] p : new String[][]{{"CASH", "صندوق"}, {"BANK", "بانک"}}) pc.addView(Ui.chip(c, p[1], p[0].equals(pf[0]), () -> { pf[0] = p[0]; rp[0].run(); })); }; rp[0].run(); l.addView(amt); l.addView(desc); l.addView(Ui.label(c, "پرداخت از")); l.addView(pc); Dialog[] dd = new Dialog[1]; l.addView(Ui.primary(c, "ثبت هزینه", () -> { if (cat[0] == 0) { Ui.toast("دسته را انتخاب کنید"); return; } dd[0].dismiss(); JSONObject b = j("description", Ui.str(desc), "paid_from", pf[0]); putNum(b, "category_id", cat[0]); putNum(b, "amount", Ui.numVal(amt, 0)); post("/accounting/expenses", b, x -> load()); })); dd[0] = Ui.sheet(c, "ثبت هزینه", l); }); }
        void newCheque() { LinearLayout l = Ui.col(c); final String[] dir = {"RECEIVED"}; LinearLayout ch = Ui.row(c); Runnable[] rd = new Runnable[1]; rd[0] = () -> { ch.removeAllViews(); ch.addView(Ui.chip(c, "دریافتی", dir[0].equals("RECEIVED"), () -> { dir[0] = "RECEIVED"; rd[0].run(); })); ch.addView(Ui.chip(c, "پرداختی", dir[0].equals("ISSUED"), () -> { dir[0] = "ISSUED"; rd[0].run(); })); }; rd[0].run(); EditText num = Ui.input(c, "شمارهٔ چک", true); EditText amt = Ui.input(c, "مبلغ", true); EditText due = DatePicker.field(c, "سررسید"); EditText bank = Ui.input(c, "بانک"); EditText party = Ui.input(c, "طرف حساب"); l.addView(ch); l.addView(num); l.addView(amt); l.addView(due); l.addView(bank); l.addView(party); Dialog[] dd = new Dialog[1]; l.addView(Ui.primary(c, "ثبت چک", () -> { try { String dd2 = dateIn(due); if (dd2 == null) { Ui.toast("سررسید لازم است"); return; } dd[0].dismiss(); JSONObject b = j("direction", dir[0], "number", Db.norm(Ui.str(num)), "bank_name", Ui.str(bank), "party_name", Ui.str(party)); putNum(b, "amount", Ui.numVal(amt, 0)); b.put("due_date", dd2); post("/accounting/cheques", b, x -> load()); } catch (Exception ignore) {} })); dd[0] = Ui.sheet(c, "ثبت چک", l); }
    }

    /* ---------------- Users & roles ---------------- */
    public static final class Users extends Screens.Screen {
        JSONArray roles = new JSONArray();
        Users(AppActivity a) { super(a); }
        public String key() { return "users"; } public String title() { return "کاربران و نقش‌ها"; }
        public void load() { loading(); get("/users/roles", r -> { roles = arr(r); get("/users", r2 -> { JSONArray ar = arr(r2); clear(); body.addView(Ui.primary(c, "+ کاربر جدید", () -> form(null))); for (int i = 0; i < ar.length(); i++) { JSONObject u = ar.optJSONObject(i); body.addView(Ui.item(c, u.optString("username") + (s(u, "full_name").isEmpty() ? "" : " · " + s(u, "full_name")), "نقش: " + u.optJSONArray("roles"), u.optBoolean("is_active") ? "فعال" : "غیرفعال", u.optBoolean("is_active") ? Ui.GREEN : Ui.RED, () -> form(u))); } LinearLayout rc = Ui.card(c, "نقش‌ها و دسترسی‌ها"); for (int i = 0; i < roles.length(); i++) { JSONObject ro = roles.optJSONObject(i); rc.addView(Ui.kv(c, ro.optString("name"), Ui.num(ro.optJSONArray("permissions") == null ? 0 : ro.optJSONArray("permissions").length()) + " دسترسی", 0)); } body.addView(rc); }); }); }
        void form(JSONObject u) { LinearLayout l = Ui.col(c); EditText un = Ui.input(c, "نام کاربری"); EditText fn = Ui.input(c, "نام کامل"); EditText pw = Ui.input(c, u == null ? "رمز عبور *" : "رمز جدید (خالی = بدون تغییر)"); pw.setInputType(InputType.TYPE_CLASS_TEXT | InputType.TYPE_TEXT_VARIATION_PASSWORD); if (u != null) { un.setText(u.optString("username")); un.setEnabled(false); fn.setText(s(u, "full_name")); } java.util.Set<String> sel = new java.util.HashSet<>(); JSONArray ur = u == null ? null : u.optJSONArray("roles"); for (int i = 0; ur != null && i < ur.length(); i++) sel.add(ur.optString(i)); LinearLayout rc = Ui.row(c); Runnable[] rd = new Runnable[1]; rd[0] = () -> { rc.removeAllViews(); for (int i = 0; i < roles.length(); i++) { String n = roles.optJSONObject(i).optString("name"); rc.addView(Ui.chip(c, n, sel.contains(n), () -> { if (sel.contains(n)) sel.remove(n); else sel.add(n); rd[0].run(); })); } }; rd[0].run(); l.addView(un); l.addView(fn); l.addView(pw); l.addView(Ui.label(c, "نقش‌ها")); l.addView(Ui.chips(c, rc)); Dialog[] d = new Dialog[1]; l.addView(Ui.primary(c, u == null ? "ایجاد کاربر" : "ذخیره", () -> { JSONObject b = j("full_name", Ui.str(fn)); try { b.put("roles", new JSONArray(sel)); } catch (Exception ignore) {} if (u == null) { if (Ui.str(pw).length() < 4) { Ui.toast("رمز حداقل ۴ کاراکتر"); return; } putIf(b, "username", Ui.str(un)); putIf(b, "password", Ui.str(pw)); d[0].dismiss(); post("/users", b, x -> load()); } else { putIf(b, "password", Ui.str(pw)); d[0].dismiss(); patch("/users/" + u.optLong("id"), b, x -> load()); } })); if (u != null && u.optLong("id") != Screens.user.optLong("id")) l.addView(Ui.danger(c, u.optBoolean("is_active") ? "غیرفعال کردن" : "فعال کردن", () -> { d[0].dismiss(); JSONObject b = j(); try { b.put("is_active", !u.optBoolean("is_active")); } catch (Exception ignore) {} patch("/users/" + u.optLong("id"), b, x -> load()); })); d[0] = Ui.sheet(c, u == null ? "کاربر جدید" : "ویرایش کاربر", l); }
    }

    /* ---------------- Audit ---------------- */
    public static final class Audit extends Screens.Screen {
        String filter = "";
        Audit(AppActivity a) { super(a); }
        public String key() { return "audit"; } public String title() { return "لاگ حسابرسی"; }
        public void load() { loading(); get("/audit?limit=150" + (filter.isEmpty() ? "" : "&action=" + Api.q(filter)), r -> { JSONArray ar = arr(r); clear(); LinearLayout ch = Ui.row(c); for (String f : new String[]{"", "LOGIN", "POS_CHECKOUT", "INVOICE_VOID", "STOCK_RECEIVE", "STOCKTAKE_APPROVE", "SETTINGS_UPDATE", "MOBILE_SYNC"}) ch.addView(Ui.chip(c, f.isEmpty() ? "همه" : f, f.equals(filter), () -> { filter = f; load(); })); body.addView(Ui.chips(c, ch)); if (ar.length() == 0) body.addView(Ui.empty(c, "رویدادی نیست")); for (int i = 0; i < ar.length(); i++) { JSONObject x = ar.optJSONObject(i); body.addView(Ui.item(c, x.optString("action"), Ui.jdate(x.optString("created_at")) + " · کاربر " + Ui.fa(s(x, "user_id")) + (s(x, "entity_type").isEmpty() ? "" : " · " + s(x, "entity_type") + " " + Ui.fa(s(x, "reference", s(x, "entity_id")))), null, 0, () -> { LinearLayout l = Ui.col(c); TextView t = Ui.text(c, "قبل:\n" + x.opt("before") + "\n\nبعد:\n" + x.opt("after"), 12, Ui.TEXT, false); t.setTextDirection(View.TEXT_DIRECTION_LTR); l.addView(t); Ui.sheet(c, x.optString("action"), l); })); } }); }
    }

    /* ---------------- Settings (all categories, generic key/value editor) ---------------- */
    public static final class Settings extends Screens.Screen {
        static final String[][] CATS = {{"store", "پروفایل فروشگاه", "store."}, {"general", "عمومی و زمان", "time.,sync."}, {"pos", "صندوق (POS)", "pos."}, {"inv", "انبار", "stocktake.,inventory."}, {"expiry", "تاریخ انقضا", "expiry."}, {"products", "محصولات", "products."}, {"barcode", "بارکد و اسکنر", "barcode."}, {"pricing", "قیمت‌گذاری", "pricing."}, {"customers", "مشتریان", "customers."}, {"ledger", "حساب دفتری", "ledger."}, {"campaign", "جشنواره و تخفیف", "marketing."}, {"sms", "پیامک", "sms."}, {"print", "پرینتر حرارتی", "printer."}, {"network", "شبکه", "network."}, {"security", "امنیت", "security."}, {"backup", "پشتیبان‌گیری", "backup."}, {"theme", "ظاهر (روشن/تیره)", "ui."}, {"update", "به‌روزرسانی", "update."}, {"license", "لایسنس", "license."}, {"mobile", "موبایل", "mobile."}, {"cloud", "همگام‌سازی ابری", "cloud."}};
        int cat = 0; JSONArray rows = new JSONArray();
        Settings(AppActivity a) { super(a); }
        public String key() { return "settings"; } public String title() { return "تنظیمات"; }
        public void load() { loading(); get("/settings", r -> { rows = arr(r); render(); }); }
        void render() {
            clear(); LinearLayout ch = Ui.row(c); for (int i = 0; i < CATS.length; i++) { final int k = i; ch.addView(Ui.chip(c, CATS[i][1], i == cat, () -> { cat = k; render(); })); } body.addView(Ui.chips(c, ch));
            String id = CATS[cat][0];
            if ("store".equals(id)) { body.addView(Ui.ghost(c, "ویرایش مشخصات فروشگاه و لوگو", () -> a.route("store"))); }
            if ("theme".equals(id)) { body.addView(Ui.ghost(c, "پوسته: خودکار ۰۷:۰۰ روشن / ۱۹:۰۰ تیره — تغییر", () -> { LinearLayout l = Ui.col(c); Dialog[] d = new Dialog[1]; for (String[] t : new String[][]{{"auto", "خودکار (۰۷:۰۰ / ۱۹:۰۰)"}, {"light", "روشن"}, {"dark", "تیره"}}) l.addView(Ui.ghost(c, t[1], () -> { d[0].dismiss(); put("/settings/theme", j("theme", t[0]), x -> { Ui.toast("ذخیره شد"); Screens.loadConfig(a); load(); }); })); d[0] = Ui.sheet(c, "پوسته", l); })); }
            if ("license".equals(id)) body.addView(Ui.ghost(c, "وضعیت لایسنس", () -> a.route("license")));
            if ("mobile".equals(id)) body.addView(Ui.ghost(c, "دستگاه‌ها و همگام‌سازی", () -> a.route("sync")));
            if ("cloud".equals(id)) body.addView(Ui.ghost(c, "وضعیت همگام‌سازی ابری", () -> a.route("cloud")));
            if ("update".equals(id)) body.addView(Ui.ghost(c, "بررسی به‌روزرسانی", () -> get("/system/update/check", r -> { JSONObject u = (JSONObject) r; Ui.toast(s(u, "message", s(u, "status")) + " · نسخهٔ فعلی " + Ui.fa(s(u, "current_version"))); })));
            if ("general".equals(id)) body.addView(Ui.ghost(c, "زمان و تقویم", () -> get("/settings/time", r -> { JSONObject t = (JSONObject) r; LinearLayout l = Ui.col(c); l.addView(Ui.kv(c, "منطقهٔ زمانی", s(t, "timezone") + " (" + s(t, "utc_offset") + ")", 0)); l.addView(Ui.kv(c, "اکنون", s(t, "jalali"), 0)); l.addView(Ui.kv(c, "تقویم", s(t, "calendar"), 0)); Ui.sheet(c, "زمان", l); })));
            if ("sms".equals(id)) body.addView(Ui.ghost(c, "صف پیامک و الگوها", () -> a.route("sms")));
            if ("print".equals(id)) body.addView(Ui.ghost(c, "سخت‌افزار و تست چاپ", () -> a.route("hardware")));
            String[] pre = CATS[cat][2].split(","); int n = 0; LinearLayout list = Ui.col(c);
            for (int i = 0; i < rows.length(); i++) { JSONObject s = rows.optJSONObject(i); String k = s.optString("key"); boolean match = false; for (String p : pre) if (k.startsWith(p)) match = true; if (!match || k.startsWith("setup.")) continue; n++;
                String val = s.optBoolean("is_secret") ? (s.optBoolean("has_value") ? "••••••" : "—") : s.optString("value"); list.addView(Ui.item(c, k.substring(k.indexOf('.') + 1).replace('.', ' ').replace('_', ' '), s(s, "description").isEmpty() ? k : s(s, "description"), Ui.fa(val.length() > 24 ? val.substring(0, 24) + "…" : val), Ui.PRIMARY, () -> editSetting(s))); }
            if (n == 0) list.addView(Ui.empty(c, "تنظیمی در این دسته نیست")); body.addView(list);
        }
        void editSetting(JSONObject s) { String k = s.optString("key"); LinearLayout l = Ui.col(c); l.addView(Ui.muted(c, s(s, "description", k))); l.addView(Ui.muted(c, k)); String cur = s.optString("value"); Dialog[] d = new Dialog[1];
            if ("true".equals(cur) || "false".equals(cur) || "1".equals(cur) && k.contains("enable") || "0".equals(cur) && k.contains("enable")) { boolean on = "true".equals(cur) || "1".equals(cur); l.addView(Ui.primary(c, on ? "غیرفعال کردن" : "فعال کردن", () -> { d[0].dismiss(); save(k, cur.matches("[01]") ? (on ? "0" : "1") : (on ? "false" : "true")); })); }
            else { EditText e = Ui.input(c, "مقدار", cur.matches("[0-9.]+")); if (!s.optBoolean("is_secret")) e.setText(cur); l.addView(e); l.addView(Ui.primary(c, "ذخیره", () -> { d[0].dismiss(); save(k, Ui.str(e)); })); }
            d[0] = Ui.sheet(c, "ویرایش تنظیم", l); }
        void save(String k, String v) { put("/settings", j("key", k, "value", v), r -> { Ui.toast("ذخیره شد"); if (k.equals("pos.currency")) Screens.loadConfig(a); load(); }); }
    }

    /* ---------------- Store profile ---------------- */
    public static final class Store extends Screens.Screen {
        Store(AppActivity a) { super(a); }
        public String key() { return "store"; } public String title() { return "مشخصات فروشگاه"; }
        public void load() { loading(); get("/settings/store-profile", r -> { JSONObject p = (JSONObject) r; clear(); LinearLayout cd = Ui.card(c, null); String[][] F = {{"name", "نام فروشگاه"}, {"legal_name", "نام قانونی"}, {"phone", "تلفن"}, {"mobile", "موبایل"}, {"address", "آدرس"}, {"city", "شهر"}, {"postal_code", "کد پستی"}, {"tax_id", "شناسهٔ مالیاتی"}, {"receipt_note", "پیام پایین رسید"}}; EditText[] es = new EditText[F.length]; for (int i = 0; i < F.length; i++) { cd.addView(Ui.label(c, F[i][1])); es[i] = Ui.input(c, F[i][1]); es[i].setText(s(p, F[i][0])); cd.addView(es[i]); } cd.addView(Ui.primary(c, "ذخیره", () -> { JSONObject b = j(); for (int i = 0; i < F.length; i++) putIf(b, F[i][0], Ui.str(es[i])); put("/settings/store-profile", b, x -> { Ui.toast("ذخیره شد"); Prefs.set("store_name", Ui.str(es[0])); }); })); body.addView(cd); LinearLayout lg = Ui.card(c, "لوگو"); if (!s(p, "logo_path").isEmpty()) { ImageView iv = Ui.img(c, 96); lg.addView(iv); Api.bg(() -> { try { byte[] bts = Api.bytes(s(p, "logo_path").startsWith("/") ? s(p, "logo_path") : "/media/" + s(p, "logo_path")); Api.ui(() -> iv.setImageBitmap(BitmapFactory.decodeByteArray(bts, 0, bts.length))); } catch (Exception ignore) {} }); lg.addView(Ui.danger(c, "حذف لوگو", () -> Api.delete("/settings/store-profile/logo", x -> load(), e -> Ui.toast(e.getMessage())))); } else lg.addView(Ui.muted(c, "لوگو از رایانه (تنظیمات → پروفایل فروشگاه) بارگذاری می‌شود و روی رسیدها چاپ می‌شود.")); body.addView(lg); }); }
    }

    /* ---------------- SMS ---------------- */
    public static final class Sms extends Screens.Screen {
        int tab = 0;
        Sms(AppActivity a) { super(a); }
        public String key() { return "sms"; } public String title() { return "پیامک"; }
        public void load() { clear(); body.addView(tabs(new String[]{"تنظیمات", "آموزش راه‌اندازی", "صف ارسال", "الگوها", "ارسال دستی"}, tab, t -> { tab = t; load(); })); LinearLayout out = Ui.col(c); body.addView(out);
            boolean local = Api.standalone();
            if (tab == 0) settings(out, local);
            else if (tab == 1) guide(out, local);
            else if (tab == 2) { if (local) queueLocal(out); else { out.addView(Ui.row(c)); LinearLayout ar0 = (LinearLayout) out.getChildAt(0); ar0.addView(Ui.small(c, "ارسال صف اکنون", () -> post("/sms/dispatch", null, r -> { Ui.toast("اجرا شد"); load(); }))); ar0.addView(Ui.small(c, "تست اتصال سامانه", () -> post("/sms/test-connection", null, r -> Ui.toast(s((JSONObject) r, "message", s((JSONObject) r, "status")))))); ar0.addView(Ui.small(c, "گزارش روزانه به مدیر", () -> post("/sms/daily-report", null, r -> { Ui.toast("در صف قرار گرفت"); load(); }))); get("/sms", r -> { JSONArray ar = arr(r); if (ar.length() == 0) out.addView(Ui.empty(c, "پیامکی ثبت نشده")); for (int i = 0; i < ar.length(); i++) { JSONObject m = ar.optJSONObject(i); out.addView(Ui.item(c, Ui.fa(m.optString("phone")), m.optString("text").replace("\n", " ") + " · " + Ui.jdate(m.optString("created_at")), label(m.optString("status"), new String[][]{{"SENT", "ارسال شد"}, {"PENDING", "در صف"}, {"RETRYING", "تلاش مجدد"}, {"FAILED", "ناموفق"}}), stColor(m.optString("status")), "FAILED".equals(m.optString("status")) ? () -> post("/sms/" + m.optLong("id") + "/retry", null, x -> { Ui.toast("در صف قرار گرفت"); load(); }) : null)); } }); } }
            else if (tab == 3) { if (local) { LinearLayout cd = Ui.card(c, "الگوی پیامک فاکتور"); EditText e = Ui.area(c, "متن الگو"); e.setText(SmsLocal.get("sms.template.invoice", SmsLocal.DEFAULT_TEMPLATE)); cd.addView(e); cd.addView(Ui.muted(c, "متغیرها: {store} {invoice} {amount} {currency}")); cd.addView(Ui.small(c, "ذخیره", () -> { SmsLocal.set("sms.template.invoice", Ui.str(e)); Ui.toast("ذخیره شد"); })); out.addView(cd); } else get("/sms/templates", r -> { JSONArray ar = arr(r); for (int i = 0; i < ar.length(); i++) { JSONObject t = ar.optJSONObject(i); LinearLayout cd = Ui.card(c, label(t.optString("kind"), new String[][]{{"invoice", "فاکتور"}, {"coupon", "کوپن"}, {"debt_reminder", "یادآوری بدهی"}, {"low_stock", "کمبود موجودی"}, {"daily_report", "گزارش روزانه"}})); EditText e = Ui.area(c, "متن الگو"); e.setText(t.optString("value")); cd.addView(e); cd.addView(Ui.muted(c, "متغیرها: " + t.optJSONArray("placeholders"))); cd.addView(Ui.small(c, "ذخیره", () -> put("/settings", j("key", t.optString("key"), "value", Ui.str(e)), x -> Ui.toast("ذخیره شد")))); out.addView(cd); } }); }
            else { LinearLayout cd = Ui.card(c, "ارسال دستی"); EditText ph = Ui.input(c, "شماره موبایل", true); EditText tx = Ui.area(c, "متن"); cd.addView(ph); cd.addView(tx); cd.addView(Ui.primary(c, "ارسال", () -> { if (local || !Api.online) { SmsLocal.enqueueAndSend(Ui.str(ph), Ui.str(tx), "manual"); Ui.toast("در صف ارسال گوشی قرار گرفت"); tab = 2; load(); } else post("/sms/send", j("phone", Db.norm(Ui.str(ph)), "text", Ui.str(tx)), r -> { Ui.toast("در صف ارسال قرار گرفت"); tab = 2; load(); }); })); out.addView(cd); }
        }
        /* settings: standalone → phone prefs; paired → PC settings table (same keys) */
        void settings(LinearLayout out, boolean local) {
            LinearLayout st = Ui.card(c, "وضعیت"); out.addView(st);
            if (local) { st.addView(Ui.kv(c, "ارسال از", "همین گوشی (بدون رایانه)", 0)); st.addView(Ui.kv(c, "پیکربندی", SmsLocal.configured() ? "کامل" : "ناقص", SmsLocal.configured() ? Ui.GREEN : Ui.AMBER)); form(out, k -> SmsLocal.get(k, ""), (k, v) -> SmsLocal.set(k, v)); }
            else { st.addView(Ui.kv(c, "ارسال از", "رایانهٔ فروشگاه (و در نبود آن، گوشی اگر فعال باشد)", 0)); getQuiet("/sms/guide", r -> { JSONObject g = ((JSONObject) r).optJSONObject("state"); if (g == null) return; st.addView(Ui.kv(c, "پیکربندی رایانه", g.optBoolean("ready") ? "کامل" : "ناقص: " + g.optJSONArray("missing"), g.optBoolean("ready") ? Ui.GREEN : Ui.AMBER)); });
                get("/settings", r -> { JSONArray rows = arr(r); java.util.Map<String, String> vals = new java.util.HashMap<>(); for (int i = 0; i < rows.length(); i++) { JSONObject x = rows.optJSONObject(i); vals.put(x.optString("key"), x.optString("value")); } form(out, k -> vals.containsKey(k) ? vals.get(k) : "", (k, v) -> { boolean secret = k.contains("password") || k.contains("api_key"); JSONObject b = j("key", k, "value", v); try { b.put("is_secret", secret); } catch (Exception ignore) {} put("/settings", b, x -> {}); if (SmsLocal.KEYS.length > 0) SmsLocal.set(k, v); }); }); }
        }
        interface Get { String v(String k); } interface Set { void v(String k, String val); }
        void form(LinearLayout out, Get g, Set s) {
            LinearLayout f = Ui.card(c, "سرویس و حساب"); out.addView(f);
            final String[] prov = {g.v("sms.provider")}; final String[] mode = {g.v("sms.melipayamak_mode").isEmpty() ? "line" : g.v("sms.melipayamak_mode")};
            LinearLayout pr = Ui.row(c); Runnable[] rd = new Runnable[1]; rd[0] = () -> { pr.removeAllViews(); for (String[] p : new String[][]{{"melipayamak", "ملی‌پیامک"}, {"kavenegar", "کاوه‌نگار"}, {"", "خاموش"}}) pr.addView(Ui.chip(c, p[1], p[0].equals(prov[0]), () -> { prov[0] = p[0]; rd[0].run(); })); }; rd[0].run(); f.addView(Ui.label(c, "سرویس پیامک")); f.addView(Ui.chips(c, pr));
            LinearLayout md = Ui.row(c); Runnable[] rm = new Runnable[1]; rm[0] = () -> { md.removeAllViews(); for (String[] p : new String[][]{{"pattern", "الگو / خط خدماتی (پیشنهادی)"}, {"line", "خط اختصاصی"}}) md.addView(Ui.chip(c, p[1], p[0].equals(mode[0]), () -> { mode[0] = p[0]; rm[0].run(); })); }; rm[0].run(); f.addView(Ui.label(c, "حالت ملی‌پیامک")); f.addView(Ui.chips(c, md));
            EditText user = Ui.input(c, "نام کاربری وب‌سرویس ملی‌پیامک"); user.setText(g.v("sms.username")); EditText pass = Ui.input(c, "رمز وب‌سرویس ملی‌پیامک"); pass.setText(g.v("sms.password")); EditText sender = Ui.input(c, "شمارهٔ خط ارسال (حالت خط اختصاصی)", true); sender.setText(g.v("sms.sender")); EditText bodyId = Ui.input(c, "شناسهٔ الگو bodyId (حالت الگو)", true); bodyId.setText(g.v("sms.melipayamak_body_id")); EditText api = Ui.input(c, "کلید API کاوه‌نگار"); api.setText(g.v("sms.api_key")); EditText admin = Ui.input(c, "شمارهٔ مدیر برای هشدار/گزارش", true); admin.setText(g.v("sms.admin_phone"));
            f.addView(user); f.addView(pass); f.addView(sender); f.addView(bodyId); f.addView(api); f.addView(admin);
            LinearLayout au = Ui.card(c, "ارسال خودکار"); out.addView(au);
            android.widget.Switch inv = new android.widget.Switch(c); inv.setText("ارسال پیامک فاکتور به محض تأیید (مستقل از چاپ رسید)"); inv.setTypeface(Ui.FONT); inv.setTextColor(Ui.TEXT); inv.setChecked(!"false".equals(g.v("sms.send_invoice"))); au.addView(inv);
            android.widget.Switch fb = new android.widget.Switch(c); fb.setText("اگر رایانه در دسترس نبود، گوشی خودش پیامک را بفرستد"); fb.setTypeface(Ui.FONT); fb.setTextColor(Ui.TEXT); fb.setChecked("true".equals(g.v("sms.phone_fallback"))); if (!Api.standalone()) au.addView(fb);
            au.addView(Ui.muted(c, "چاپ رسید را می‌توانید در «تنظیمات → صندوق» خاموش کنید؛ پیامک همچنان می‌رود. مشتری باید شمارهٔ موبایل داشته باشد (مشتری آزاد پیامک نمی‌گیرد)."));
            out.addView(Ui.primary(c, "ذخیرهٔ تنظیمات پیامک", () -> { s.v("sms.provider", prov[0]); s.v("sms.melipayamak_mode", mode[0]); s.v("sms.username", Ui.str(user)); s.v("sms.password", Ui.str(pass)); s.v("sms.sender", Db.norm(Ui.str(sender))); s.v("sms.melipayamak_body_id", Db.norm(Ui.str(bodyId))); s.v("sms.api_key", Ui.str(api)); s.v("sms.admin_phone", Db.norm(Ui.str(admin))); s.v("sms.send_invoice", inv.isChecked() ? "true" : "false"); s.v("sms.phone_fallback", fb.isChecked() ? "true" : "false"); Ui.toast("ذخیره شد"); load(); }));
            out.addView(Ui.ghost(c, "تست اتصال (اعتبار پنل)", () -> { if (Api.standalone() || !Api.online) Api.bg(() -> { try { String cr = SmsLocal.melipayamakCredit(); Api.ui(() -> Ui.toast("اتصال برقرار است · اعتبار: " + Ui.fa(cr))); } catch (Exception e) { Api.ui(() -> Ui.toast("خطا: " + e.getMessage())); } }); else post("/sms/test-connection", null, r -> Ui.toast(s((JSONObject) r, "detail", s((JSONObject) r, "status")))); }));
        }
        void guide(LinearLayout out, boolean local) {
            out.addView(Ui.note(c, "چه کارهایی باید در پنل ملی‌پیامک انجام دهید؟", "این آموزش دقیقاً همان مراحل نسخهٔ رایانه است. پس از انجام هر مرحله، مقادیر را در تب «تنظیمات» وارد کنید."));
            for (String[] g : SmsLocal.GUIDE) { LinearLayout cd = Ui.card(c, g[0]); cd.addView(Ui.body(c, g[1])); out.addView(cd); }
            out.addView(Ui.ghost(c, "باز کردن سایت ملی‌پیامک", () -> { try { a.startActivity(new Intent(Intent.ACTION_VIEW, android.net.Uri.parse("https://www.melipayamak.com"))); } catch (Exception e) { Ui.toast("مرورگر در دسترس نیست"); } }));
            out.addView(Ui.ghost(c, "باز کردن پنل کاوه‌نگار", () -> { try { a.startActivity(new Intent(Intent.ACTION_VIEW, android.net.Uri.parse("https://panel.kavenegar.com"))); } catch (Exception e) { Ui.toast("مرورگر در دسترس نیست"); } }));
        }
        void queueLocal(LinearLayout out) {
            LinearLayout ar0 = Ui.row(c); out.addView(ar0); ar0.addView(Ui.small(c, "ارسال صف اکنون", () -> Api.bg(() -> { int n = SmsLocal.flush(); Api.ui(() -> { Ui.toast(Ui.fa(String.valueOf(n)) + " پیامک ارسال شد"); load(); }); })));
            JSONArray q = SmsLocal.queue(); if (q.length() == 0) out.addView(Ui.empty(c, "پیامکی ثبت نشده"));
            for (int i = q.length() - 1; i >= 0; i--) { JSONObject m = q.optJSONObject(i); String st = m.optString("status"); out.addView(Ui.item(c, Ui.fa(m.optString("phone")), m.optString("text").replace("\n", " ") + " · " + Ui.jdate(m.optString("at")) + (m.optString("error").isEmpty() ? "" : " · " + m.optString("error")), label(st, new String[][]{{"SENT", "ارسال شد"}, {"PENDING", "در صف"}, {"RETRY", "تلاش مجدد"}, {"FAILED", "ناموفق"}}), stColor("RETRY".equals(st) ? "PENDING" : st), "FAILED".equals(st) ? () -> { SmsLocal.retry(m.optString("id")); load(); } : null)); }
        }
    }

    /* ---------------- Hardware ---------------- */
    public static final class Hardware extends Screens.Screen {
        Hardware(AppActivity a) { super(a); }
        public String key() { return "hardware"; } public String title() { return "سخت‌افزار"; }
        public void load() { loading(); get("/hardware/health", r -> { JSONObject h = (JSONObject) r; clear(); LinearLayout cd = Ui.card(c, "وضعیت لحظه‌ای (رایانه)"); for (String[] k : new String[][]{{"printer", "چاپگر حرارتی"}, {"scanner", "بارکدخوان"}, {"cash_drawer", "کشوی پول"}}) cd.addView(Ui.kv(c, k[1], label(s(h, k[0]), new String[][]{{"CONNECTED", "متصل"}, {"DISCONNECTED", "قطع"}, {"UNKNOWN", "نامشخص"}}), stColor(s(h, k[0])))); cd.addView(Ui.kv(c, "اسکنر این گوشی", "دوربین (ZXing) — آماده", Ui.GREEN)); body.addView(cd);
            LinearLayout ts = Ui.card(c, "آزمایش"); ts.addView(Ui.ghost(c, "چاپ رسید آزمایشی", () -> post("/hardware/test/print", null, x -> Ui.toast(s((JSONObject) x, "message", "ارسال شد"))))); ts.addView(Ui.ghost(c, "باز کردن کشوی پول", () -> post("/hardware/test/drawer", null, x -> Ui.toast(s((JSONObject) x, "message", "ارسال شد"))))); ts.addView(Ui.ghost(c, "کشف بارکدخوان‌های رایانه", () -> get("/hardware/scanner/discover", x -> { JSONArray ar = arr(x); Ui.toast(ar.length() == 0 ? "دستگاهی یافت نشد" : Ui.num(ar.length()) + " دستگاه"); }))); ts.addView(Ui.ghost(c, "آزمایش دوربین گوشی", () -> a.scan("آزمایش اسکنر", code -> Ui.toast("خوانده شد: " + code)))); body.addView(ts);
            LinearLayout dv = Ui.card(c, "دستگاه‌های ثبت‌شده"); body.addView(dv); getQuiet("/hardware", x -> { JSONArray ar = arr(x); if (ar.length() == 0) dv.addView(Ui.muted(c, "دستگاهی ثبت نشده")); for (int i = 0; i < ar.length(); i++) { JSONObject d = ar.optJSONObject(i); dv.addView(Ui.item(c, d.optString("name"), d.optString("device_type") + " · " + s(d, "connection") + (d.optInt("paper_width_mm") > 0 ? " · " + Ui.num(d.optInt("paper_width_mm")) + "mm" : ""), d.optBoolean("is_enabled") ? "فعال" : "غیرفعال", d.optBoolean("is_enabled") ? Ui.GREEN : Ui.MUTED, null)); } dv.addView(Ui.small(c, "+ ثبت دستگاه", () -> { LinearLayout l = Ui.col(c); final String[] ty = {"PRINTER"}; LinearLayout ch = Ui.row(c); Runnable[] rd = new Runnable[1]; rd[0] = () -> { ch.removeAllViews(); for (String[] t : new String[][]{{"PRINTER", "چاپگر"}, {"SCANNER", "بارکدخوان"}, {"CASH_DRAWER", "کشو"}, {"SCALE", "ترازو"}}) ch.addView(Ui.chip(c, t[1], t[0].equals(ty[0]), () -> { ty[0] = t[0]; rd[0].run(); })); }; rd[0].run(); EditText n = Ui.input(c, "نام"); EditText cn = Ui.input(c, "اتصال (USB / COM3 / 192.168.1.50:9100)"); EditText pw = Ui.input(c, "عرض کاغذ mm (چاپگر: ۵۸ یا ۸۰)", true); l.addView(ch); l.addView(n); l.addView(cn); l.addView(pw); Dialog[] dd = new Dialog[1]; l.addView(Ui.primary(c, "ثبت", () -> { dd[0].dismiss(); JSONObject b = j("device_type", ty[0], "name", Ui.str(n), "connection", Ui.str(cn)); if (!Ui.str(pw).isEmpty()) putNum(b, "paper_width_mm", (int) Ui.numVal(pw, 80)); post("/hardware", b, y -> load()); })); dd[0] = Ui.sheet(c, "دستگاه جدید", l); })); }); }); }
    }

    /* ---------------- Diagnostics ---------------- */
    public static final class Diagnostics extends Screens.Screen {
        Diagnostics(AppActivity a) { super(a); }
        public String key() { return "diagnostics"; } public String title() { return "تست اتصالات"; }
        public void load() { clear(); LinearLayout top = Ui.card(c, "تست کامل سامانهٔ رایانه"); top.addView(Ui.muted(c, "هر بررسی I/O واقعی انجام می‌دهد: پایگاه داده، API، چاپگر، اسکنر، پیامک، لایسنس، زمان، دیسک، پشتیبان…")); top.addView(Ui.primary(c, "اجرای تست (بدون اینترنت)", () -> run(false))); top.addView(Ui.ghost(c, "اجرای تست کامل (با سرویس‌های خارجی)", () -> run(true))); body.addView(top);
            LinearLayout ph = Ui.card(c, "این گوشی"); ph.addView(Ui.kv(c, "اتصال به رایانه", Api.online ? "برقرار" : "قطع", Api.online ? Ui.GREEN : Ui.RED)); ph.addView(Ui.kv(c, "آدرس", Api.base, 0)); ph.addView(Ui.kv(c, "صف ارسال", Ui.num(Db.opCount()), 0)); ph.addView(Ui.kv(c, "پایگاه دادهٔ محلی", Ui.fa(Db.count("products") + " کالا / " + Db.count("batches") + " بچ"), 0)); ph.addView(Ui.ghost(c, "تست پینگ رایانه", () -> Api.bg(() -> { long t = System.currentTimeMillis(); boolean ok = Api.health(); long ms = System.currentTimeMillis() - t; Ui.toast(ok ? "پاسخ در " + Ui.num(ms) + " میلی‌ثانیه" : "پاسخی نیامد"); }))); body.addView(ph);
            LinearLayout hs = Ui.card(c, "اجراهای قبلی"); body.addView(hs); getQuiet("/diagnostics/history", r -> { JSONArray ar = arr(r); if (ar.length() == 0) hs.addView(Ui.muted(c, "—")); for (int i = 0; i < Math.min(10, ar.length()); i++) { JSONObject x = ar.optJSONObject(i); hs.addView(Ui.item(c, Ui.jdate(x.optString("started_at")), "موفق " + Ui.num(x.optInt("passed")) + " · ناموفق " + Ui.num(x.optInt("failed")) + " · ردشده " + Ui.num(x.optInt("skipped")), null, 0, () -> get("/diagnostics/runs/" + x.optLong("run_id", x.optLong("id")), y -> show((JSONObject) y)))); } });
            LinearLayout sq = Ui.card(c, "صف کارهای رایانه (پیامک، همگام‌سازی…)"); body.addView(sq); getQuiet("/diagnostics/sync/stats", r -> { JSONObject st = (JSONObject) r; sq.addView(Ui.kv(c, "در انتظار", Ui.num(st.optDouble("pending")), 0)); sq.addView(Ui.kv(c, "ناموفق", Ui.num(st.optDouble("failed")), st.optDouble("failed") > 0 ? Ui.RED : 0)); sq.addView(Ui.small(c, "اجرای صف اکنون", () -> post("/diagnostics/sync/run", null, x -> { Ui.toast("اجرا شد"); load(); }))); }); }
        void run(boolean ext) { Ui.toast("در حال اجرا… (چند ثانیه)"); Api.post("/diagnostics/run?include_external=" + ext, null, r -> show((JSONObject) r), e -> Ui.toast(e.getMessage())); }
        void show(JSONObject run) { LinearLayout l = Ui.col(c); l.addView(Ui.kv(c, "نتیجه", "موفق " + Ui.num(run.optInt("passed")) + " · ناموفق " + Ui.num(run.optInt("failed")) + " · ردشده " + Ui.num(run.optInt("skipped")), run.optInt("failed") > 0 ? Ui.RED : Ui.GREEN)); JSONArray ch = run.optJSONArray("checks"); for (int i = 0; ch != null && i < ch.length(); i++) { JSONObject x = ch.optJSONObject(i); l.addView(Ui.item(c, x.optString("name"), x.optString("detail"), label(x.optString("status"), new String[][]{{"PASS", "موفق"}, {"FAIL", "ناموفق"}, {"SKIP", "ردشده"}, {"WARN", "هشدار"}}), "PASS".equals(x.optString("status")) ? Ui.GREEN : "FAIL".equals(x.optString("status")) ? Ui.RED : Ui.MUTED, null)); } Ui.sheet(c, "نتیجهٔ تست", l); load(); }
    }

    /* ---------------- Support (tickets + two-way chat + attachments) ---------------- */
    public static final class Support extends Screens.Screen {
        Support(AppActivity a) { super(a); }
        public String key() { return "support"; } public String title() { return "پشتیبانی"; }
        public boolean autoRefresh() { return true; }
        public void load() { clear(); body.addView(Ui.primary(c, "+ درخواست جدید", this::create)); LinearLayout st = Ui.card(c, null); body.addView(st); getQuiet("/support/status", r -> { JSONObject s = (JSONObject) r; st.addView(Ui.kv(c, "کانال پشتیبانی", s.optBoolean("configured") ? "پیکربندی‌شده" : "پیکربندی‌نشده", s.optBoolean("configured") ? Ui.GREEN : Ui.AMBER)); st.addView(Ui.kv(c, "دریافت پاسخ", s.optBoolean("inbox_ready") ? "فعال" : "غیرفعال", 0)); st.addView(Ui.kv(c, "در صف ارسال", Ui.num(s.optDouble("pending")), 0)); }); LinearLayout list = Ui.col(c); body.addView(list); if (Api.standalone()) { st.removeAllViews(); st.addView(Ui.kv(c, "کانال پشتیبانی", "مستقیم از گوشی (اینترنت)", Ui.GREEN)); st.addView(Ui.kv(c, "کد نصب", SupportRelay.installCode(), 0)); JSONArray ar = SupportRelay.tickets(); if (ar.length() == 0) list.addView(Ui.empty(c, "درخواستی ثبت نشده")); for (int i = ar.length() - 1; i >= 0; i--) { JSONObject t = ar.optJSONObject(i); list.addView(Ui.item(c, Ui.fa(t.optString("number")) + " · " + t.optString("subject"), t.optString("type_label") + " · " + Ui.jdate(t.optString("created_at")), t.optString("status_label") + (t.optInt("unread") > 0 ? "\n" + Ui.num(t.optInt("unread")) + " پاسخ جدید" : ""), t.optInt("unread") > 0 ? Ui.PRIMARY : stColor(t.optString("status")), () -> a.open(new Ticket(a, t), true))); } Api.bg(() -> { if (SupportRelay.poll() > 0) Api.ui(this::load); }); return; } getQuiet("/support/tickets", r -> { JSONArray ar = arr(r); if (ar.length() == 0) list.addView(Ui.empty(c, "درخواستی ثبت نشده")); for (int i = 0; i < ar.length(); i++) { JSONObject t = ar.optJSONObject(i); list.addView(Ui.item(c, Ui.fa(t.optString("number")) + " · " + t.optString("subject"), t.optString("type_label") + " · " + t.optString("priority_label") + " · " + Ui.jdate(t.optString("created_at")), t.optString("status_label") + (t.optInt("unread") > 0 ? "\n" + Ui.num(t.optInt("unread")) + " پاسخ جدید" : ""), t.optInt("unread") > 0 ? Ui.PRIMARY : stColor(t.optString("status")), () -> a.open(new Ticket(a, t), true))); } }); }
        void create() { if (Api.standalone()) { createLocal(a, this::load); return; } getQuiet("/support/types", r -> { JSONObject ty = (JSONObject) r; JSONArray types = ty.optJSONArray("types"), pris = ty.optJSONArray("priorities"); LinearLayout l = Ui.col(c); final String[] tp = {types != null && types.length() > 0 ? types.optJSONObject(0).optString("id") : "BUG"}; final String[] pr = {"NORMAL"}; LinearLayout tc = Ui.row(c); Runnable[] rd = new Runnable[1]; rd[0] = () -> { tc.removeAllViews(); for (int i = 0; types != null && i < types.length(); i++) { JSONObject x = types.optJSONObject(i); tc.addView(Ui.chip(c, x.optString("label"), x.optString("id").equals(tp[0]), () -> { tp[0] = x.optString("id"); rd[0].run(); })); } }; rd[0].run(); LinearLayout pc = Ui.row(c); Runnable[] rp = new Runnable[1]; rp[0] = () -> { pc.removeAllViews(); for (int i = 0; pris != null && i < pris.length(); i++) { JSONObject x = pris.optJSONObject(i); pc.addView(Ui.chip(c, x.optString("label"), x.optString("id").equals(pr[0]), () -> { pr[0] = x.optString("id"); rp[0].run(); })); } }; rp[0].run(); EditText subj = Ui.input(c, "موضوع *"); EditText desc = Ui.area(c, "شرح مشکل"); EditText contact = Ui.input(c, "راه تماس (موبایل)", true); l.addView(Ui.label(c, "نوع")); l.addView(Ui.chips(c, tc)); l.addView(Ui.label(c, "اولویت")); l.addView(pc); l.addView(subj); l.addView(desc); l.addView(contact); Dialog[] d = new Dialog[1]; l.addView(Ui.primary(c, "ارسال درخواست", () -> { if (Ui.str(subj).length() < 3) { Ui.toast("موضوع کوتاه است"); return; } d[0].dismiss(); JSONObject b = j("type", tp[0], "priority", pr[0], "subject", Ui.str(subj), "description", Ui.str(desc), "contact", Ui.str(contact), "device", "android-native/" + Version.NAME); Api.post("/support/tickets", b, x -> { Ui.toast("درخواست " + Ui.fa(((JSONObject) x).optString("number")) + " ثبت شد"); load(); }, e -> { if (e.offline()) { Sync.queue("SUPPORT_TICKET", b, "درخواست پشتیبانی", null); Ui.toast("آفلاین — پس از اتصال ارسال می‌شود"); } else Ui.toast(e.getMessage()); }); })); d[0] = Ui.sheet(c, "درخواست پشتیبانی", l); }); }
    }
    static final String[][] LOCAL_TYPES = {{"BUG", "ثبت خرابی / اشکال"}, {"FEATURE", "درخواست افزودن امکان ویژه"}, {"QUESTION", "سؤال / راهنمایی"}, {"LICENSE", "لایسنس و فعال‌سازی"}, {"TRAINING", "آموزش / راه‌اندازی"}, {"OTHER", "سایر"}};
    static void createLocal(AppActivity a, Runnable after) {
        LinearLayout l = Ui.col(a); final String[] tp = {"BUG"}; LinearLayout tc = Ui.row(a); Runnable[] rd = new Runnable[1]; rd[0] = () -> { tc.removeAllViews(); for (String[] x : LOCAL_TYPES) tc.addView(Ui.chip(a, x[1], x[0].equals(tp[0]), () -> { tp[0] = x[0]; rd[0].run(); })); }; rd[0].run();
        EditText subj = Ui.input(a, "موضوع *"); EditText desc = Ui.area(a, "شرح مشکل"); EditText contact = Ui.input(a, "راه تماس (موبایل)", true); contact.setText(Prefs.get("store_mobile", ""));
        l.addView(Ui.label(a, "نوع")); l.addView(Ui.chips(a, tc)); l.addView(subj); l.addView(desc); l.addView(contact); Dialog[] d = new Dialog[1];
        l.addView(Ui.primary(a, "ارسال درخواست", () -> { if (Ui.str(subj).length() < 3) { Ui.toast("موضوع کوتاه است"); return; } d[0].dismiss(); String label = tp[0]; for (String[] x : LOCAL_TYPES) if (x[0].equals(tp[0])) label = x[1]; JSONObject b = Api.obj("type", label, "priority", "عادی", "subject", Ui.str(subj), "description", Ui.str(desc), "contact", Ui.str(contact), "device", "android-native/" + Version.NAME); Ui.toast("در حال ارسال…"); Api.bg(() -> { String err = SupportRelay.send(b); Api.ui(() -> { Ui.toast(err == null ? "درخواست ثبت و ارسال شد" : err); after.run(); }); }); }));
        d[0] = Ui.sheet(a, "درخواست پشتیبانی", l);
    }
    public static final class Ticket extends Screens.Screen {
        final JSONObject t; byte[] pendingFile; String pendingName;
        Ticket(AppActivity a, JSONObject t) { super(a); this.t = t; }
        public String key() { return "support"; } public String title() { return "گفت‌وگو با پشتیبانی"; }
        public boolean autoRefresh() { return true; }
        public void load() { if (Api.standalone()) { loadLocal(); return; } loading(); get("/support/tickets/" + t.optLong("id") + "/messages", r -> { JSONArray ar = arr(r); clear(); LinearLayout hd = Ui.card(c, Ui.fa(t.optString("number")) + " · " + t.optString("subject")); hd.addView(Ui.muted(c, t.optString("type_label") + " · " + t.optString("status_label") + " · " + Ui.jdate(t.optString("created_at")))); if (!s(t, "description").isEmpty()) hd.addView(Ui.body(c, s(t, "description"))); body.addView(hd);
            for (int i = 0; i < ar.length(); i++) { JSONObject m = ar.optJSONObject(i); boolean in = "IN".equals(m.optString("direction")) || "INBOUND".equals(m.optString("direction")); LinearLayout bub = Ui.col(c); bub.setBackground(Ui.rounded(in ? Ui.CARD : Ui.PRIMARY, in ? Ui.BORDER : 0, 16)); bub.setPadding(Ui.dp(12), Ui.dp(8), Ui.dp(12), Ui.dp(8)); LinearLayout.LayoutParams lp = Ui.margin(Ui.lp(android.view.ViewGroup.LayoutParams.WRAP_CONTENT, android.view.ViewGroup.LayoutParams.WRAP_CONTENT), in ? 0 : 40, 0, in ? 40 : 0, 8); lp.gravity = in ? android.view.Gravity.START : android.view.Gravity.END; bub.setLayoutParams(lp); if (!s(m, "text").isEmpty()) bub.addView(Ui.text(c, s(m, "text"), 14, in ? Ui.TEXT : 0xFFFFFFFF, false)); if (!s(m, "attachment_url").isEmpty()) { TextView at = Ui.text(c, "📎 " + s(m, "attachment_name", "پیوست"), 12, in ? Ui.PRIMARY : 0xFFFFFFFF, true); at.setOnClickListener(v -> a.startActivity(new Intent(Intent.ACTION_VIEW, Uri.parse(Api.base + s(m, "attachment_url"))))); bub.addView(at); } bub.addView(Ui.text(c, (in ? "پشتیبانی" : "شما") + " · " + Ui.jdate(s(m, "created_at")) + (in ? "" : " · " + s(m, "status_label")), 10, in ? Ui.MUTED : 0xCCFFFFFF, false)); body.addView(bub); }
            if (ar.length() == 0) body.addView(Ui.empty(c, "هنوز پیامی رد و بدل نشده"));
            if (!"CLOSED".equals(t.optString("status"))) { LinearLayout cmp = Ui.card(c, null); EditText tx = Ui.area(c, "پیام شما…"); cmp.addView(tx); TextView fn = Ui.muted(c, pendingName == null ? "" : "پیوست: " + pendingName); cmp.addView(fn); LinearLayout br = Ui.row(c); br.addView(Ui.small(c, "📎 پیوست عکس", () -> pickFile())); View sp = new View(c); sp.setLayoutParams(Ui.weight(1)); br.addView(sp); br.addView(Ui.primary(c, "ارسال", () -> send(Ui.str(tx)))); cmp.addView(br); cmp.addView(Ui.ghost(c, "بستن درخواست", () -> Ui.confirm(c, "درخواست بسته شود؟", () -> post("/support/tickets/" + t.optLong("id") + "/close", null, x -> a.back())))); body.addView(cmp); }
            post("/support/poll", null, x -> {}); }); }
        void loadLocal() {
            clear(); SupportRelay.markRead(t.optInt("id")); JSONObject cur = t; for (int i = 0; i < SupportRelay.tickets().length(); i++) if (SupportRelay.tickets().optJSONObject(i).optInt("id") == t.optInt("id")) cur = SupportRelay.tickets().optJSONObject(i);
            LinearLayout hd = Ui.card(c, Ui.fa(cur.optString("number")) + " · " + cur.optString("subject")); hd.addView(Ui.muted(c, cur.optString("type_label") + " · " + cur.optString("status_label") + " · " + Ui.jdate(cur.optString("created_at")))); if (!s(cur, "description").isEmpty()) hd.addView(Ui.body(c, s(cur, "description"))); body.addView(hd);
            JSONArray ar = cur.optJSONArray("messages"); if (ar == null) ar = new JSONArray();
            for (int i = 0; i < ar.length(); i++) { JSONObject m = ar.optJSONObject(i); boolean in = "IN".equals(m.optString("direction")); LinearLayout bub = Ui.col(c); bub.setBackground(Ui.rounded(in ? Ui.CARD : Ui.PRIMARY, in ? Ui.BORDER : 0, 16)); bub.setPadding(Ui.dp(12), Ui.dp(8), Ui.dp(12), Ui.dp(8)); LinearLayout.LayoutParams lp = Ui.margin(Ui.lp(android.view.ViewGroup.LayoutParams.WRAP_CONTENT, android.view.ViewGroup.LayoutParams.WRAP_CONTENT), in ? 0 : 40, 0, in ? 40 : 0, 8); lp.gravity = in ? android.view.Gravity.START : android.view.Gravity.END; bub.setLayoutParams(lp); bub.addView(Ui.text(c, m.optString("text"), 14, in ? Ui.TEXT : android.graphics.Color.WHITE, false)); bub.addView(Ui.text(c, (in ? "پشتیبانی · " : "شما · ") + Ui.jdate(m.optString("created_at")), 10, in ? Ui.MUTED : 0xCCFFFFFF, false)); body.addView(bub); }
            if (ar.length() == 0) body.addView(Ui.empty(c, "هنوز پاسخی دریافت نشده — پاسخ پشتیبانی همین‌جا نمایش داده می‌شود"));
            LinearLayout cmp = Ui.card(c, null); EditText tx = Ui.area(c, "پیام شما…"); cmp.addView(tx); cmp.addView(Ui.primary(c, "ارسال", () -> { if (Ui.str(tx).isEmpty()) return; Ui.toast("در حال ارسال…"); Api.bg(() -> { String err = SupportRelay.reply(t.optInt("id"), Ui.str(tx)); Api.ui(() -> { Ui.toast(err == null ? "ارسال شد" : err); load(); }); }); })); cmp.addView(Ui.ghost(c, "بررسی پاسخ جدید", () -> Api.bg(() -> { SupportRelay.poll(); Api.ui(this::load); }))); body.addView(cmp);
        }
        void pickFile() { Intent i = new Intent(Intent.ACTION_GET_CONTENT); i.setType("image/*"); i.addCategory(Intent.CATEGORY_OPENABLE); a.pickCb = (uri) -> { try { java.io.InputStream in = a.getContentResolver().openInputStream(uri); java.io.ByteArrayOutputStream bo = new java.io.ByteArrayOutputStream(); byte[] buf = new byte[8192]; int n; while ((n = in.read(buf)) > 0) bo.write(buf, 0, n); in.close(); pendingFile = bo.toByteArray(); pendingName = "photo-" + System.currentTimeMillis() + ".jpg"; Ui.toast("پیوست آماده (" + Ui.num(pendingFile.length / 1024) + " KB)"); load(); } catch (Exception e) { Ui.toast("خواندن فایل ناموفق"); } }; a.startActivityForResult(Intent.createChooser(i, "انتخاب عکس"), AppActivity.REQ_PICK); }
        void send(String text) { if (text.isEmpty() && pendingFile == null) { Ui.toast("متن یا پیوست لازم است"); return; } Ui.toast("در حال ارسال…"); Api.bg(() -> { try { Api.upload("/support/tickets/" + t.optLong("id") + "/messages", new String[][]{{"text", text}}, pendingFile == null ? null : "file", pendingName, pendingFile, "image/jpeg"); pendingFile = null; pendingName = null; Api.ui(() -> { Ui.toast("ارسال شد"); load(); }); } catch (Api.ApiError e) { Ui.toast(e.getMessage()); } }); }
    }
}
