const { JSDOM } = require("jsdom"); const fs = require("fs"); const BASE="http://127.0.0.1:8000";
(async () => {
  const html = fs.readFileSync("" + require("path").join(__dirname, "..", "..", "frontend") + "/index.html","utf8");
  const dom = new JSDOM(html,{url:BASE+"/",runScripts:"outside-only",pretendToBeVisual:true});
  const {window}=dom; const errors=[];
  window.addEventListener("error",e=>errors.push("onerror: "+e.message));
  window.fetch=async(i,init)=>{const u=typeof i==="string"&&i.startsWith("http")?i:BASE+i;return fetch(u,init);};
  window.matchMedia=window.matchMedia||(()=>({matches:false,addEventListener(){},addListener(){}}));
  window.navigator.serviceWorker={register:async()=>{}};
  window.HTMLElement.prototype.requestFullscreen=async()=>{};
  const login=await fetch(BASE+"/api/auth/login",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:"username=admin&password=admin123"});
  window.localStorage.setItem("token",(await login.json()).access_token);
  window.eval(fs.readFileSync("" + require("path").join(__dirname, "..", "..", "frontend") + "/app.js","utf8"));
  await new Promise(r=>setTimeout(r,1500));
  const wait=(ms)=>new Promise(r=>setTimeout(r,ms));
  await window.go("products"); await wait(1500);
  const d=window.document;
  console.log("starter card:", !!d.querySelector("#p-starter"), "| info:", (d.querySelector("#p-starter-info")||{}).textContent.slice(-60));
  await window.go("reports"); await wait(1200);
  [...d.querySelectorAll("#rep-tabs button")].find(b=>b.textContent.includes("ماهانه")).click(); await wait(1500);
  console.log("monthly report:", d.querySelector("#rep-out").textContent.slice(0,80));
  await window.go("settings"); await wait(1200);
  const tabs=[...d.querySelectorAll(".set-tab")];
  tabs.find(t=>t.textContent.includes("پروفایل")).click(); await wait(1200);
  console.log("logo upload ctl:", !!d.querySelector("#sp-logo-up"), !!d.querySelector("#sp-logo-preview"));
  tabs.find(t=>t.textContent.includes("به‌روزرسانی")).click(); await wait(2500);
  console.log("update box:", (d.querySelector("#upd-box")||{textContent:"MISSING"}).textContent.replace(/\s+/g," ").slice(0,160));
  console.log("update settings rows:", d.querySelectorAll("#set-body input").length);
  await window.go("hardware"); await wait(1000);
  console.log("h-conn placeholder:", (d.querySelector("#h-conn")||{}).placeholder);
  const fontCss=fs.readFileSync("" + require("path").join(__dirname, "..", "..", "frontend") + "/styles.css","utf8");
  console.log("font-face bundled:", /@font-face[\s\S]*Vazirmatn-Regular\.woff2/.test(fontCss));
  console.log("errors:", errors);
  if (errors.length) process.exit(1);
  console.log("UI v1.2 SMOKE OK");
})();
